### ISSUE TITLE
Replace green checkmarks with an alternative -- maybe "Leave" button?

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#103]
Folks have been commenting that this icon looks confusing:

![screen shot 2016-04-09 at 10 45 35 pm](https://cloud.githubusercontent.com/assets/4512699/14408326/d36a1fae-fea4-11e5-93d7-7ecd855b0999.jpg)

Maybe we should change it to be a button that says "Leave."

**Comment by sergeant-q** [comment]
Yep. I made mention of this and it was totally confusing to me! Unfortunately, it is not as intuitive as one would think.

**Comment by lpatmo** [comment]
![screen shot 2016-04-14 at 12 52 03 am](https://cloud.githubusercontent.com/assets/4512699/14520774/311546a4-01db-11e6-9ee6-913c9a5c166e.jpg)

Not sure if the button should say "leave" or "joined" or "Un-RSVP"... which one looks better?!

**Comment by lpatmo** [comment]
Branch: `git checkout 103-green-checkmarks`

**Comment by sergeant-q** [comment]
My initial feeling is to use the **Leave** button. Perhaps add a tooltip when you hover it to provide better explanation that this means you are essentially un-RSVP'ng yourself.

**Comment by adachiu** [comment]
@lpatmo  It's getting messy with too many perceived affordances. There's about 6 things that look clickable and we'll need to simplify it.

![screen shot 2016-04-14 at 9 47 57 am](https://cloud.githubusercontent.com/assets/13413986/14536188/ffe325d8-0225-11e6-897a-e79bba2b0305.png)

The following points correspond to the numbers marked in the screenshot:

**1** How important is it to show the time that a hangout is completed? The hangout date and time is already shown under the hangout title so completion time could be removed, to help us remove unnecessary elements.

**2** This is the personal dash right? When a user joins a hangout, the hangout would on their personal dash. With that being said, there's no need to have a "joined" button since it's already obvious. If they didn't join it, it shouldn't be on their dash. So I suggest replacing the "Joined" with "UPCOMING in X days/mins/hours" because it's information that's more useful.

**3,4,5** Since this hangout title is the CTA blue, it's already perceived that it could open to show more detail. In that case, we could have the "copy" and "edit" button removed since those could be within the hangout modal (is it a modal or a dedicated page?).

**7** The "copy" button could be removed and be placed inside the hangout details page. Also, I would suggest using a different word. Maybe "Duplicate Hangout"  or "Reschedule Hangout"

**Comment by sergeant-q** [comment]
@adachiu I am not sure how valuable point `#1` is but I know it's being used on the current site.

`#2` - this button is actually designed to allow a user to **join** (RSVP) that scheduled hangout. If the user has already _joined_ the hangout, then the button will reflect either **Leave** or one of the other aforementioned recommendations that @lpatmo is trying to get feedback on.

For points on `#3, #4 and #5` - There are valid ones.  We _can_ move these buttons/icons to the hangout details page to make the home page hangouts list more cleaner. I think it's a UX decision of intuitiveness over convenience. These are modals that pop up by the way. 

`#7` - the intent of this is to quickly _duplicate_ the hangout (creating a new one) with the existing topic and description pre-populated. So, I agree we can certainly rename this to "duplicate". Moving it to the hangout details page could make it more difficult for folks to find but again, this is the same debate of intuitiveness over convenience as noted above.

**Comment by adachiu** [comment]
@sergeant-q 

#2 is this for the home-logged-in page? The screenshot is very similar to the Personal dash hangout list so I'm a bit confused as to which it is.

If it is the home-logged-in page, then I agree that the "join" and "leave" button should be present. 

For the personal-dash, the hangout list should only show what the user already joined and completed since the list is specific to the user. For the user to join new hangouts, they would have to go to the home-logged-in page to see the full hangout list. 

In any case, we could test all of these to optimize the design :)

**Comment by sergeant-q** [comment]
@adachiu 

That is correct. `#2` is for logged-in users.  As for the personal dashboard a.k.a (profile page) - I agree with your points. I think that's already something your mock ups allude to.

@lpatmo thoughts?

**Comment by lpatmo** [comment]
#1 - I could go for removing the "X minutes/hours" ago to unclutter the interface.

#2 - This was actually a screenshot from the home page, but re: showing "UPCOMING IN X hours/minutes" -- I like that! The only issue is the "joined" or "leave" button is something the user can click on to un-RSVP themselves from a hangout. So it could be a smaller button, but there needs to be something they can click on still.

Hmmm... maybe it could be a hyperlink under the "UPCOMING IN X"? And when clicked on the entire section would look like the $cta-blue "JOIN" button again.

#3 - The edit/trash icons look like a lot here because I'm the creator of all of these hangouts, but they would only appear for next to posts a user had created. I'm personally in favor of keeping them there -- I like the ability to immediately being able to edit or trash a post without clicking an extra step. 

#7 - Maybe some sort of "recurring" icon next to the edit/trash buttons? Again, based on my experience creating posts I really like the ability to click on this and immediately have a modal open up that I can submit -- generally makes hangout cloning/creating a lot easier IMO.

**Comment by lpatmo** [comment]
@adachiu @sergeant-q How does this look?

![screen shot 2016-04-17 at 12 08 54 am](https://cloud.githubusercontent.com/assets/4512699/14585643/afd36c3a-0430-11e6-90b2-1547509291d7.jpg)

**Comment by lpatmo** [comment]
Update: I also changed the icons around a bit.

![screen shot 2016-04-17 at 12 31 25 am](https://cloud.githubusercontent.com/assets/4512699/14585727/d88a8228-0433-11e6-933c-a4a2ab8ba05e.jpg)

Do you think this looks better?

**Comment by sergeant-q** [comment]
So, are we removing the icons in place of "duplicate" and "edit"??

**Comment by lpatmo** [comment]
@sergeant-q Yep. "Copy" is now named "Duplicate" and instead of the pencil icon, it says "Edit." Do you think it looks better or worse?

**Comment by adachiu** [comment]
@lpatmo if I'm the host of a hangout, it won't show "remove RSVP" for me right?

The "upcoming hangout" doesn't have to be blue since it's not clickable. It could follow the same style as "COMPLETED"

**Comment by sergeant-q** [comment]
@lpatmo I think keeping the **"delete"** icon wouldn't be so bad as opposed to just an **"x"**.

**Comment by lpatmo** [comment]
@adachiu Yep, if a host is clicking on the link, a popup will appear and tell them they can't remove themselves from the hangout. 

@sergeant-q Done, kept the "delete" icon!

![screen shot 2016-04-18 at 9 00 59 pm](https://cloud.githubusercontent.com/assets/4512699/14627381/af3dfd7a-05a8-11e6-91a7-ac079f45b2ee.jpg)

**Comment by lpatmo** [comment]
@adachiu Distalx proposes cleaning up the meta content:

![image](https://cloud.githubusercontent.com/assets/4512699/14628102/9c109b8e-05af-11e6-8af8-b6c7da985bbb.png)

What do you think?

Ignore the tags and the comment icon for now.

**Comment by adachiu** [comment]
@lpatmo I like how it cuts down the amount of text. The "people joined" icon might need a tooltip making it even more clear that it means people joined. Personally, i think it's fine without the tooltip, but who knows some people might think it means number of people already in hangout or number of people RSVPed only.

I like the 3 dots icon to  show the actions available. It definitely makes the whole page cleaner 👌🏻  Why is report an option here? I thought reports would only be reporting comments and users.

Beside the username could say "Host" so it's clear why there is a username. Or there could be a tooltip on hover.

Why does the checkmark mean? completed? I think we should keep the "Completed" and "Upcoming" because it's more clear.

**Comment by distalx** [comment]
@adachiu 
Why is "report an option" here? 
In the list that appears beneath the three-dot action bar, users will only be able to see the options available to them.
 
"Why does the checkmark mean? Completed? I think we should keep the "Completed" and "Upcoming" text because it's more clear."

I think we should use less text and try to invent our (Code Buddies) vocabulary, e.g. before Twitter "retweet" was not a thing. Similarly, Facebook changed the meaning of the thumbs up to "like", and later, Instagram branded heart as a "like" icon .

In our case, we could have:
Dot Circles outline === in progress 
Dot Circles outline + join button === in progress 
Checkmark === completed 
Join button === upcoming

**Comment by lpatmo** [comment]
![screen shot 2016-04-18 at 11 28 34 pm](https://cloud.githubusercontent.com/assets/4512699/14629709/5b4ba5ae-05bd-11e6-9917-abe37a5d5ed5.jpg)

I added the three dots!

It's a little weird when clicked on, though... had to make it `position: relative;` instead of `position: absolute;`; otherwise it would get hidden.

If you have a solution for this problem, feel free to commit to the branch: `git checkout 103-green-checkmarks` `git pull`

**Comment by adachiu** [comment]
@distalx We could definitely try to create a CB vocabulary. However, I do think "COMPLETED" is more clear than a checkmark though because a checkmark could mean a variety of things: completed hangout, joined hangout, rsvp-ed for hangout, successfully created hangout, etc. We could have a tooltip for the checkmark I suppose.

In any case, we'll optimize the design once we get more testing done. 👌🏻

**Comment by adachiu** [comment]
Some additional thoughts on @distalx screenshot.

1. We shouldn't use the same "person" (teaching hangout) icon for the "people joined" since it could confuse users. 
2. In the screenshot @lpatmo posted, the "# joined" is very clear and it doesn't need any tooltips. If we substitute too many text with icons, we'll need a lot of tooltips. When there are so many tooltips, it could get annoying when hovering over things.
2. Since each hangout title is clickable and opens up a more detailed popup/page, we do not need the comments icon on the Join Hangouts list. This simplifies the list view. The key things we want users to see are: title, time, join. create hangout. Everything else is extra or "nice to have." The "nice to have" information could all go into the detailed hangout page(or pop up).

**Comment by distalx** [comment]
@lpatmo I believe this has been merged. #108
