### ISSUE TITLE
IDEA: "upcoming" list of hangouts on the home page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#130]
When we switch over to the CBV2 site from hangouts.codebuddies.org, one key difference is that if you're not logged in, you won't be able to at-a-glance see all the upcoming hangouts anymore. And that could be factor in your decision in whether or not you want to log in/join the website.

Two alternative ideas:

1) Put an "upcoming" section on the not-logged-in-view homepage that displays the 5 upcoming hangouts.
2) This section will disappear if there are 0 upcoming hangouts, and will instead display 5 recently completed hangouts.
3) If there is only 1 upcoming hangout, it will only display that 1 upcoming hangout.

There could be also be an argument to just displaying the most recent 5 hangouts, whether or not they were completed or hangout. *shrug*

Anyway, this issue is NOT necessary for the launch. Just putting this out there because it'll be a key change to what people are used to (being able to see all the upoming/completed hangouts publicly on the home page without having logged in.)

**Comment by adachiu** [comment]
Seeing at-a-glance from a non-logged-in view would be very beneficial due to the convenience of looking at the updates.

For new users, the recent/upcoming hangouts list would pique their interest to learn more about CB hangouts.

@lpatmo Are you referring to modifying the existing non-logged-in homepage? Specifically the section where there's the image of the example hangouts?

**Comment by sergeant-q** [comment]
I think this is a valid point from an initial interest perspective. On the flipside, it does kind of give it a feel of exclusivity and that in itself can pique my interest to sign up.

**Comment by lpatmo** [comment]
Closing; this issue is a duplicate of #225.
