### ISSUE TITLE
BUG: #todayilearned page doesn't exist on cbv2

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#148]
The #todayilearned bot links to a page that doesn't exist in v2.

**Comment by lpatmo** [comment]
Tasks:

- [ ] Create a new page (http://codebuddies.org/learnings)
- [ ] Inside it, include the text: "Learnings coming soon."

Let's reuse the template from templates/other/about.html or templates/other/faq.html.

I'll open up another bug to discuss what the page should look like with the content, but for now someone can work on create a new URL route in this meteor app. :) (Hint: look at `lib/routes.js`)

This is a `good-for-beginners` issue.

**Comment by khaleelsyed** [comment]
Can I give this a shot?

**Comment by camilleriluke** [comment]
Sure marking it claimed and in progress. Enjoy @khaleelsyed :)

**Comment by khaleelsyed** [comment]
Cheers @camilleriluke I'll keep you posted on my progress.

**Comment by khaleelsyed** [comment]
I'm not sure if I can continue on this issue. I've been really struggling to get [meteor-js](https://aur.archlinux.org/packages/meteor-js/) installed on my Arch Linux box and I don't think I can keep on this if I've not got Meteor.

**Comment by camilleriluke** [comment]
@khaleelsyed Did you follow the instructions @ https://www.meteor.com/install?

**Comment by khaleelsyed** [comment]
@camilleriluke I'll try giving a shot using those official docs.

**Comment by khaleelsyed** [comment]
I tired installing using the official docs method: [This was the output](https://gist.github.com/khaleelsyed/117e225f3e8dc4036a46f13bd43de7bf). I still continued anyway assuming it should be installed anyway. After I try running the command `meteor --settings settings-development.json`, I get the issue `Unexpected mongo exit code 1. Restarting.` and I was able to get in the mongo shell without any error messages from the daemon. I tried restarting the service using `sudo systemctl stop mongodb` and then `sudo systemctl start mongodb` and the same issue occurs when I make an attempt to start the meteor app.

After looking around I figured out that the issue possibly might be because my `.meteor/local/db/local.ns` might be missing but I can't find any fix around on the internet for that. I found that on this [thread here](https://forums.meteor.com/t/mongodb-exit-code-1-while-using-meteor/16711/9).

But this is the [total output of running the meteor app](https://gist.github.com/khaleelsyed/01219372148a4e5e8ac03e2a26df3b4e).

Any suggestions on how to go around all this mess? But would this whole process be easier if I used a Ubuntu environment instead? I can get Ubuntu up on a virtual machine if all this would be easier on a Ubuntu Box.

Really sorry for such a messy reply, thanks a lot for co-operating! I tried not to put up my path/environment variable file as it contains quite a chunk of my API keys and it just seemed a huge task to make an attempt to try and mask them out.

If you require any further logs and etc, please let me know. Much appreciated.

**Comment by distalx** [comment]
@khaleelsyed Try this in order. and let me know the output.
```
meteor reset
meteor npm install
npm run meteor:dev
```

**Comment by khaleelsyed** [comment]
@distalx  I still got a mongo exit code 1 when I ran that. Really sorry for such a late reply.

**Comment by ricjon** [comment]
I think I can give this a shot also if it's ok.

**Comment by khaleelsyed** [comment]
@ricjon You can take over, I don't mind.

**Comment by ricjon** [comment]
Why is this still open? My pr is merged and it is also in production now.

**Comment by lpatmo** [comment]
@ricjon Thanks for the flag! losing this issue. 

On a related note, we should probably start taking advantage of github's feature that lets us close issues by referencing it in a git commit.
