### ISSUE TITLE
Make hangout start/end time optional

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#193]
Noticing that having to commit to a time for a hangout is a lot of pressure.

Let's make the start/end time optional, and include a "now" link so that the "start" field prefills with the time right now to help those who still want to create a hangout that starts immediately, instead of TBD in the future.

**Comment by crazcalm** [comment]
Is this still an issue? If so, I would like to take an crack at it.

**Comment by lpatmo** [comment]
@crazcalm Hi Marcus -- this is still an issue! :)

Happy to discuss, since I'm not entirely sure of what it should look like. The main goals:

- Allow end-time setting to be optional, but still be there if a user wants to fix it (maybe the date/time box could be hidden behind a `Set end time` link)
- Creators of a hangout and admins of the site can click a button to mark a hangout as completed after it starts, and un-mark the hangout as completed if they change their minds.
- When a hangout is marked as completed, in the backend, the "end" key for the hangout is set to the current time.
![screen shot 2016-09-29 at 6 46 26 pm](https://cloud.githubusercontent.com/assets/4512699/18978152/1af9097c-8675-11e6-87ac-9a11e0604ad9.jpg)

**Comment by crazcalm** [comment]
@lpatmo I think I understand the main goals. I also do not know what it should look like. I will try to get the functionality down first. We can tweak the UI after I prove to myself that I can actually do this ticket, lol.

Questions:
- Is the start time still mandatory? I ask because the ticket title is slightly different from the goals you just mentioned.
- If one does not choose an end time on creation, how should the end time be stored as in the database? I ask because it seems like all the times are currently being stored in a date format. Also, I am not sure if other parts of the code base depend on the end time being in a certain format.

**Comment by lpatmo** [comment]
- Hah, yeah, sorry for the confusion! I was initially thinking no, but I'm leaning towards it being auto-populated with the current time (as it currently is)....
- Good question. If a date format is necessary, maybe a safe "never ending" datetime would be 1 month in the future calculated from the start time.

**Comment by crazcalm** [comment]
@lpatmo I have not been worrying the UI yet, but I think I have most of the functionality down.

So, if the end time is not set by the creator of the event, then I set it for 28 days in the future (the p tag has a onclick function attached to display the date picker).
![screen shot 2016-10-02 at 6 52 24 pm](https://cloud.githubusercontent.com/assets/3482344/19024446/dae35266-88d1-11e6-8a33-8cf22006c4be.png)
In the item list, I check to see if the start and end time differ by a value greater than 27 days. If so, I replace the end date with "To Be Announced"
![screen shot 2016-10-02 at 6 51 57 pm](https://cloud.githubusercontent.com/assets/3482344/19024449/dd5f108e-88d1-11e6-8490-ca3a2727a25a.png)

In term functionality, it this suitable?

Also, I have a question about the button that allows creators and admins to mark a hangout as complete.

1. If a person decides to mark a hangout as complete and then un-marks it, what should the end time be? I ask because you want the end time to be set when the hangout is marked as completed, but, if they decide to un-mark it, then the end time will already be in the past.

2. What page should this button be on? I assume it will be on the edit hangout page, but I want make sure before I start.

**Comment by adachiu** [comment]
@crazcalm @lpatmo One month in the future is a long time.
What if there is an auto-end time if the creator forgets to mark it as complete? (ex. after 24 hours from starting time)

It seems safe to have the auto-end/complete within 24hours from the starting time since the hangouts have all been within a day's time.

After the auto-end is triggered, we could have an email notification to tell the creator that it has been auto-ended on their behalf. If it is un-true that the hangout ended, the creator can un-mark the completion. The timer can reset to auto-end in another 24 hours, unless the creator sets their own end time.

If the creator intends to have multi-day hangouts, they can either:
1) Create multiple hangouts
2) Create one hangout with an end time set in the future day (this could be 28 days in the future or anything they want)

What are your thoughts?

**Comment by crazcalm** [comment]
@adachiu @lpatmo One month in the future is a long time. 24 hours does sound more reasonable. However, if you want to change it in the future, it should be an easy change.

@adachiu In terms of your thoughts on triggering an email after the auto-end has been reach, I am not sure that is possible. I have not looked into the email system, so I do not know how it works. Also, "auto-end" and the current "end time" are one and the same (in terms of the database). What this means is that there will be no way to know for sure if the end time was set by the user or automatically. We can assume that any events that last for 24 hours was an event where the end time was auto-fiiled, but that is still an assumption.

In terms of the mark/unmark a hangout as completed, if that marker is placed on the edit hangout page, then we can set the end time to whatever we want (it does not have to be tied to the auto end time done on the create hangout modal). For example, when a person marks a hangout as complete, we can set the end-time to the current time. When a person marks a previous completed hangout as not completed, we can set the end time to the current time + x hours (x being whatever default we decided). Since this is on the edit page, the user still has the option to change the end time. Note: I am referring to altering the values of the end datetime picker in the UI. Nothing would be sent to the backend until the user clicks "Edit your Hangout" on the edit hangout page.

Summary:
- 24 hours for the auto end time sounds good to me.
- I am not sure how the email notification would work, but if you do want to proceed with it, I think that should be done in another ticket (possible a follow up issue?).
- I think the mark/unmark the completion of an hangout button would be easiest to do on the hangout edit page. 

I am going to start working on the "mark/unmark the completion of a hangout" button.

Cool?

**Comment by adachiu** [comment]
@crazcalm  RE auto-end: if the email notifications system is not achievable, would it be possible to trigger a notification on `https://codebuddies.org/notifications` ? We could set up another ticket for this.

RE mark/unmark: When you say the `edit page`, you mean the `edit modal` window right? I agree on your points for the mark/unmark button feature.

Additionally, I think that Instead of `edit your hangout` as the button name, we could say something else so it isn't redundant with the modal window's title. Perhaps we could have the button be named `Save changes` ?

**Comment by crazcalm** [comment]
@adachiu After I finish the mark/unmark button, I can look into the email notification, but I would like for that to be another ticket.

You are right. I did mean the edit modal window.

I may not of been clear on the "edit you hangout" part. 
![screen shot 2016-10-02 at 10 35 28 pm](https://cloud.githubusercontent.com/assets/3482344/19026232/2f2912d8-88f1-11e6-92bf-5509ad8ca80a.png)

The edit modal already has a button called "Edit your Hangout". The user clicks that button to save the changes. The mark/unmark button that I would create will most likely be a check box on that modal called "completed". 

If a hangout is completed, then that box will be checked. If not, that box will be unchecked. If the state of the box goes from checked to unchecked, then I will change the end time date picker to sometime in the future. If the state of the box goes from unchecked to checked, then I will change the end time date picker to the current time.

Note that none of the changes will be saved until the user clicks the "Edit your Hangout" button.

**Comment by distalx** [comment]
Some thoughts on this one.

What if we give a replace the end date/time picker with a drop down menu.

![image](https://cloud.githubusercontent.com/assets/11193792/19026528/aa6771d0-8944-11e6-8f3b-a07822418378.png)

And if time has set to undefined === never-ending, give user (host) the ability to end that hangout. 

![image](https://cloud.githubusercontent.com/assets/11193792/19026539/ce2b8606-8944-11e6-9a38-5540780912f6.png)

**Comment by adachiu** [comment]
@crazcalm I mean the "Edit your Hangout" button can be called "Save changes" instead. Because it's more clear that the changes are being saved. Besides, the modal window already has the "Edit your hangout" title at the very top. From a UX perspective, it would be more clear to the user if the blue button was called "Save changes" 😄 

@distalx Interesting idea. In your wireframe, does the start date also include the start time? People may want to know the start time so they can commit to going online to join. Knowing the start time is more important than having a set end time. The end time can always be changed, either shorter or longer, but the start time is crucial for people to show up.

I think that the edit option should be there regardless of which timeframe they select (not just for the `undefined` option) because unforeseen circumstances may prompt the creators to change the time selection.

**Comment by distalx** [comment]
@adachiu, yes it does.

**Comment by lpatmo** [comment]
Sorry for the slow response. This thread got long. :)

Thank you for your work, @crazcalm! To answer your original two questions:

> If a person decides to mark a hangout as complete and then un-marks it, what should the end time be? I ask because you want the end time to be set when the hangout is marked as completed, but, if they decide to un-mark it, then the end time will already be in the past.

If they un-mark it, then the end time should be 24 hours from the time right *now*.

> What page should this button be on? I assume it will be on the edit hangout page, but I want make sure before I start.

I think it makes most sense for this button to be below where the "launch the hangout" button is on the single post page, as shown in @distalx's second mockup above. (And we can figure out where exactly it should also be on the new homepage view later; don't have to worry about it now.)

- In general, I agree that setting it to be 24 hours is better than setting it to to be 28 days.
- The email/Slack notification features are large enough they could be one or two separate bugs -- so yeah, agree we shouldn't worry about it now.

I really, really like @distalx's mockup of the select box containing the select box of end time options instead of a "Set end time?" link. :) 

@crazcalm -- feel free to open a pull request now if you'd like to pass on the changing-the-link-to-a-select box; otherwise, if you can change 28 days to 24 hours, that'd be great.

And let us know if you'd like any help re: adding the "End this hangout" button to `templates/hangout/hangout.html` -- i.e., feel free to push up your branch.

Thanks!

**Comment by lpatmo** [comment]
@adachiu And good observation re:

> I mean the "Edit your Hangout" button can be called "Save changes" instead. Because it's more clear that the changes are being saved. Besides, the modal window already has the "Edit your hangout" title at the very top. From a UX perspective, it would be more clear to the user if the blue button was called "Save changes"

I can file a new `good-for-beginners` issue for that (pretty easy, so someone can take it for a quick PR).

**Comment by crazcalm** [comment]
I just created the pull request. I am pretty new at this so I am not sure if I was suppose to do something special for it to show up here, but you can find it there https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/281

In terms of the UI elements, I am happy to pass that on to someone who knows what they are doing (because I do not).

In terms of the end hangout button, I am not sure of how to go about putting the button on that page. It makes sense that it is there, but I am not sure of how to construct the edit call to modify the hangout. If someone is willing to help me, then I can try to add it to the already existing pull request. If not, you can make that button into another ticket.

Also, after it made the PR, I realized that the profile page also has a list of hangouts, but I am not sure template corresponds to that list. As of right now, it is missing the "To Be Announced" wording for hangouts that are 24 hours.

**Comment by lpatmo** [comment]
Thanks for opening up the PR (yay, first Hacktoberfest PR!) and pushing up your branch, @crazcalm. :) I'll make some commits re: the UI.

**Comment by distalx** [comment]
@lpatmo are we using `select option` for end dates ?

**Comment by lpatmo** [comment]
This feature has been deployed!! 🎆
