### ISSUE TITLE
Adjustments to the hangout status/"currently working on" UI

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#25]
1. We need tooltips to appear over each icon to explain what each hangout type means.
2. The hangout status the user selected should be colored in after they've selected it.
3. Can we make the borders surrounding the names bolder, or put hangout status icons next to the names below, to make it clearer what the colors mean? (@adachiu -- any thoughts?)
4. Wondering if we should add something extra to motivate people to fill in a currently working on status. For example, if their current status is blank, highlight the textarea red?

http://cbv2-staging2.meteor.com/

![screen shot 2016-02-11 at 1 01 34 am](https://cloud.githubusercontent.com/assets/4512699/12972545/07a31884-d05b-11e5-8a50-68b26c00b17f.jpg)

**Comment by adachiu** [comment]
1. Yes, we'll need tooltips. Also, there's a slight disconnect right now with the top and bottom boxes. I
think it would be more clear and intuitive if we connect the top and bottom. I'll look into improving this ux/ui.
2. You mean the status icon should stay filled after the user clicks update? If we keep the status icon filled, then maybe the status should remain in input area after clicking update as well. It could also have the time stamp there. One reason to keep the status and icon fill "live" within the input area is because the user could quickly revisit what they have inputted as their status without needing to scroll the list of "people online learning" to find out what their status was (this is if there's 20+ people online and the user is at the very bottom of the list).
3. Or we can just fill the name rectangle with the hangout color. Are we using material design icons btw? since it has the "no video" icon whereas fontawesome doesn't? If we merge the top and bottom boxes, we could even have a small area that describes the hangouts so we don't need to put icons beside each user status, which could become very redundant or visually busy.
4. I wouldn't recommend making the text area red since red alerts are usually perceived as negative. If we try the method mentioned in above to keep the text status within the status input area, along with a time stamp, then it "may" (have to be tested to be sure) incentivize users to update their old status.
5. The text in "people are online learning" area shouldn't be blue since blue is a CTA color, unless we're making those links to message the users.

I can create new mocks (including the profile/dashboard) and string them together in an invisionapp prototype to get some testing done so the user test results could guide our design decisions going forward. Thoughts?

**Comment by lpatmo** [comment]
1. Cool -- and I see it's done in your newest mockups!
2. ++
3. I like how you've designed the hangout names and statuses in V7. 
4. Good point -- let's try it out with how you've designed it so far! And then see if we can make improvements when it's first deployed/in user testing.
5. ++

Thank you Ada!

**Comment by lpatmo** [comment]
Closing this issue because someone's taking the tooltips bug.
