### ISSUE TITLE
Bonus: everyone who signed up for a deleted hangout should get a notification that it was cancelled.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#40]
Was originally thinking the notification should be e-mailed to everyone RSVPed, but we could have it send Slack notifications as well.

**Comment by sgtquezada** [comment]
The slack API method to send a message is restricted to either a #channel or @user but not multiple users unless I loop through the method call.  Does it make more sense (and efficient) to notify the channel instead once the hangout has been deleted?   

Looking for some feedback on the approach.

**Comment by lpatmo** [comment]
@sgtquezada Hmm... good question.

I'm leaning towards NOT notifying a channel on Slack -- I think it'll get too annoying. (And already people are hesitating to `@channel` to make an announcement, so we shouldn't have it notifying deletions either.)

Three alternatives: 
1) loop through the method call
2) Just return a list of users who signed up for the hangout, and in the second alert box link to something like: https://codebuddiesmeet.slack.com/messages/@user1,user2,user3,user4/ (the way this link is formatted actually works!)
3) Figure out a way to send notifications via email instead of Slack. (Probably more complicated, but I do like that it's not relying so much on Slack, which not 100% of people check). Mailgun gives us 10K transactional emails for free: https://www.mailgun.com/pricing

**Comment by sgtquezada** [comment]
@lpatmo I might reconsider my approach and go with email notifications instead. I am making a pretty big assumption people are either logged into Slack via their mobile devices or desktop. This would be the only way someone would get notified. Which is risky as you noted.

Option 2 is not bad but it does leave it up to the hangout host to follow through and notify users via the link, which opens this up to manual intervention and human error.

I looked at the code and our slack login functionality is not currently pulling in the user's email address :(

Issue #26 will resolve this for us though! Once we get this up and running, I can start exploring the email notification option with mailgun.

**Comment by sheldonbarnes** [comment]
@lpatmo @sgtquezada : In terms of "Figure out a way to send notifications via email instead of Slack", might consider something like sendgrid.com.  They have an API for sending email.   I believe it is free for up to 10k emails per month, and after that you would have to subscribe to a plan.  I've used it before on a demo project, and it is pretty cool.  

https://sendgrid.com/docs/API_Reference/Web_API/index.html
https://sendgrid.com/pricing?mc=SendGrid%20Documentation

**Comment by lpatmo** [comment]
Thanks for the sendgrid suggestion! I just gave @sgtquezada an account for mailgun, which also offers a free tier. Not sure which one is cheaper/better, though. I think SendGrid is actually more popular, so may be worth trying out and comparing.

**Comment by lpatmo** [comment]
@sgtquezada Just realized this issue is similar to "send a reminder to participants that a hangout is happening soon." So once we figure this out, the second would be easier. Win!

**Comment by sgtquezada** [comment]
@lpatmo hmm. I think we may need to create a separate module/class to send notifications out at one point since it sounds like there will be a need to have it for multiple uses cases.  It's something I can work on after I complete this feature.  

@sheldonbarnes we went with mailgun since Meteor already integrates with it as part of their 'Email' package.  So, it's a much straightforward configuration and we will simply use our own account to remove the  daily email limitation.

**Comment by sgtquezada** [comment]
Code has been merged into the `master` branch! Ready for review and closure.
