### ISSUE TITLE
I'm interested buttons should display when Today I learned tab is clicked

### ISSUE THREAD

**Issue by sheldonbarnes** [codebuddiesdotorg/cb-v2-scratch#48]
![screen shot 2016-03-04 at 8 02 06 pm](https://cloud.githubusercontent.com/assets/10457072/13544491/6f081a7e-e244-11e5-865e-635e54215102.png)
![screen shot 2016-03-04 at 8 02 14 pm](https://cloud.githubusercontent.com/assets/10457072/13544492/6f0badc4-e244-11e5-8525-55288674e432.png)

When the "Today I learned" tab is clicked, the 3 buttons for I'm interested in does not display.  

    <span class="interest">I'm interested in:</span>
    {{#if isWorking type}}

The span should be brought within the if statements, or the buttons should also be displayed.

**Comment by adachiu** [comment]
@sheldonbarnes The "I'm interested in" text and buttons don't need to show in the "Today I learned" tab because TIL does not update the status feed on the "I'm working on" tab. The two tabs have separate content.

You can refer to the mock ups @lpatmo posted.

**Comment by adachiu** [comment]
@lpatmo I like the hearts idea, but it's getting cluttered with the heart on the right and the "+2" numbers on the left. Instead of having the heart button and the numbers separated on both ends, why not have it all on one side. Also I think the upvote arrow icon is more like saying "good job" than the heart icon? :P 

Example posted:

![screen shot 2016-03-05 at 12 45 10 am](https://cloud.githubusercontent.com/assets/13413986/13546725/94c5cc1c-e26b-11e5-8136-5b19352f7978.png)

**Comment by sheldonbarnes** [comment]
I will move the text to only show on the working side.

**Comment by sheldonbarnes** [comment]
Easy fix.  Committed to branch if someone wants to take it for a spin:

https://github.com/codebuddiesdotorg/cb-v2-scratch/tree/fix/issue-48-interested-in-learning-buttons

**Comment by lpatmo** [comment]
@sheldonbarnes Fix looks good, thanks! Have merged into master.
