### ISSUE TITLE
Can we do an integration when a hangout is created be published to a channel to slack?

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#54]
Hat tip to @foxiae for suggesting.

**Comment by sgtquezada** [comment]
I thought we didn't want to do this? Spam a channel?

**Comment by lpatmo** [comment]
I think we didn't want delete events to notify a channel, but created events might make sense...

**Comment by sergeant-q** [comment]
For clarification, is the intent to notify a slack channel when a new hangout has been created (scheduled) on the CB site or when the actual hangout is live and in-progress?

Also - thinking about this feature seems like tagging might be a pre-req to implement this more effectively. Thoughts?

**Comment by foxiae** [comment]
Tagging would need to be a pre-req if we wanted to push to a particular channel that a hangout has been created/scheduled/going on. Looking at the API, it doesn't seem that hard to do.

We could create one channel for news channel on slack that could also push when a hangout has been created/started/any other sort of news from the site - if that's something that would be of interest. 

We could also create a channel for the TIL posts. (I just really want to integrate to Slack as much as possible lol)

**Comment by sergeant-q** [comment]
LOL - I know slack is a fantastic communication tool so it's hard to resist integrating it into an app! On the flipside, we are essentially banking on Slack if we start going down this approach and mark it as our de facto communication/authentication tool and mechanism. 

This has been brought up as a concern as not everyone in the community is using Slack. However, it certainly doesn't mean it's a bad thing to force (or encourage?) folks to use it if they want to be part of and participate in the CB community/site. Personally, I'm all for it. Just need a consensus.

Assuming we go with Slack - I agree a simpler approach that wouldn't require tagging would be to create a `#news` or `#announcements` channel in the Slack community to use as the channel to fire off alerts to whenever a new hangout has been created/scheduled.  I'd like more feedback on this before proceeding with this feature.  I had already put some minor functionality together to test the Slack webhooks and use their API to notify a channel.  It is pretty straightforward.

@lpatmo what are your thoughts on this?

**Comment by lpatmo** [comment]
I think the simpler approach makes sense: creating a #news or #hangouts channel that would populate with alerts about hangouts created on the Slack.

Both types of notifications also make sense, IMO:
1) when the hangout is initially created
2) 10 minutes before a hangout starts

I'm not quite sure if each of these notifications should be prepended with `@channel` (might get too annoying if hangout creation becomes more active), but there's a way each user to disable @channel sounds directly in the Slack settings:
![screen shot 2016-03-16 at 6 33 34 pm](https://cloud.githubusercontent.com/assets/4512699/13830818/ad23d14e-eba5-11e5-9470-ba6e92aa58f7.jpg)

And later, if this new channel becomes more busy, and once we have tags implemented, we can figure out how to have these notifications appear in separate channels.

**Comment by adachiu** [comment]
@sergeant-q A dedicated channel for hangouts/announcements would be effective. I've seen other Slack groups use this approach to announce news and it works really well. Keeps things organized in one place.

@lpatmo for the "10 minutes before a hangout starts" alert, wouldn't it be great if there's a Slack bot that could message joined users :stuck_out_tongue: ... or maybe email alerts if users choose to have the notification.

**Comment by lpatmo** [comment]
@adachiu We have the "email alerts" version of that feature in this issue: https://github.com/codebuddiesdotorg/cb-v2-scratch/issues/49 :)

A few thoughts on Slack:
- The most people I've noticed having the CB slack open at the same time has been ~50 people. We're still a pretty small community. I get the sense that a lot of people register, don't really understand how to use Slack (or forget that they registered because they ignore the generic email notifications from Slack that there's been activity in a channel), and end up dropping out. Therefore, I think an email notification might be more effective than a Slack bot notification.
- My only worry re: relying on Slack is if the community gets too active and the channel announcements get too much, but thankfully we're not there yet!

**Comment by distalx** [comment]
I believe that we should consider some kind of _following_ or _subscription_ mechanism for that.
and suppose, If we are sending all the alerts to one specific or subject specific channel we might lose the _attention span_ of the users because nobody likes appearing _notifications_ or sound of _bling bling_ on duration of every 5 or even on ~ 20 some minutes, user might find this annoying. 

Follow or Subscription mechanism  will might prove also beneficial in terms of  if decide to sent  _push notifications_ on a later stage.

And still while/if we are considering the heavy integration with slack, 
As @adachiu mentioned.
We should explore the possibilities of sending alert via private message to particular users who has shown their interest in specific hangout.


PS. If we implement follow or sub mechanism we might also able to display _Popular_ or even _Trending_ Hangouts on codebuddies.

**Comment by foxiae** [comment]
I didn't think it would be such a huge annoyance to user if this sort of integration was made. I just know, knowing myself, I won't check CBv2 for new hangouts to be created. If people don't publicize it in the channel (really the only way currently I know when a hangout is created), I don't know about it. 

The current process for creating hangouts/publicizing them is 1) created hangout on website, 2) publicize to @channel that hangout is created, 3) (if applicable) remind channel that hangout is happening. All of this process can be automated for users.

We don't have a lot of traffic right now with hangout creation, so if we publish to a the hangout creation to that particular Slack channel, I don't think it'll disturb the peace that much. 
But an announcement or hangout page would probably be better. I rather a channel get flooded with messages about a hangout creation than my email (which already gets flooded with other things).

If someone just wants to create a hangout to solve a particular problem with people they're discussing in the channel, we could implement a switch that has 'Publish to Slack Channel?'. The default can be yes, but for certain cases - if the meeting supposed to be for a couple of people - that hangout doesn't have to be broadcast to the whole community.

**Comment by sergeant-q** [comment]
I'm with @foxiae on this one. I see a few online bootcamps and similar sites follow this pattern.  [thinkful.com] (http://thinkful.com) comes to mind. They send a slack notification to a general channel announcing their 'session' (hangout for us) is about to start in X minutes.  They do not `@channel` so this makes it less intrusive but nevertheless a reminder was sent out for those interested.

**A couple of benefits that come to mind with this approach**
1. more visibility to a hangout that most would have not been aware of in the first place
2. the more participants, the more engagement and desire to have more people host more hangouts
3. can easily share a hangout link to others!

I think it makes more sense to send out a notification to a slack channel 20-30 minutes *before* the actual hangout begins.  Personally, If I get an email reminder telling me a hangout is going to start tomorrow, I will forget about it.  I'm not checking that email again. Email notifications make a lot of sense on cancellations.

If we send a slack message directly to a user that has RSVP'd, we lose out on point number **1** as noted above.  

I am not opposed to email notifications/reminders. However, I think this is best served through a formal **newsletter** that can be sent out on a weekly basis highlighting folks on any upcoming scheduled hangouts.

**As a side note:** 
Since we are doing heavy integration with Slack, why don't we add something on the home page that gives users a direct link to our Slack room? (I think this is already being done on the current site).  Make it very visible and help guide them to use it.  At the end of the day, if you are interested in joining the community, using slack is a big part of interacting with fellow code buddies. Let's encourage it!

**Comment by sergeant-q** [comment]
There's a small bug or error actually showing up on the console indicating the `extend` method is not found on `undefined` on the custom slack function.  Will create fix branch for this.  This is **not** impacting the actual functionality but need to resolve the error. 

`functions.js:18Uncaught TypeError: Cannot read property 'extend' of undefined`

**Comment by sergeant-q** [comment]
I have conditionally fixed this error by wrapping the function inside an `if (Meteor.isServer)` block.  I am a little confused as to why this needs to be done if from the **meteor docs**, it states anything under the **/lib** directory is loaded first and on **both** the server and client. 

The error is because the package variable `slack` is not available on initial page load so it can't find the `extend` property (method) on it. I might be missing something or not enough knowledge on how to handle making variables/objects globally available within Meteor.  I'll continue to do research but for now I will submit a PR for this.

**Comment by sergeant-q** [comment]
I believe this has been merged. So we can close it now!

**Comment by lpatmo** [comment]
Closing!
