### ISSUE TITLE
One-click create a new hangout button

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/cb-v2-scratch#7]
Create a new (google?) hangout with a click of a button.

**Comment by Luxisapex** [comment]
Found this

https://github.com/withpulp/wpt-hangouts

and it works fine for this issue, but I have doubts regarding how to implement further wanted features.

**Comment by lpatmo** [comment]
Haven't played around with it, but... nice find, @Luxisapex! Thanks!

**Comment by Luxisapex** [comment]
Did anyone actually look into making the actual hangouts yet, or is it just what is on the staging site?

**Comment by sgtquezada** [comment]
Not yet. The meteor package you mentioned seems to lack some config options so will require to either build upon this package or code it ourselves outside a package.

**Comment by wuworkshop** [comment]
Haven't read all the documentation yet, but this might be useful.

Google+ Hangout button
https://developers.google.com/+/hangouts/button

**Comment by wuworkshop** [comment]
A Hangouts alternative - https://developer.appear.in/

**Comment by lpatmo** [comment]
Appear.in looked really promising, but we ran into a few issues: 

- Audio was not working on Google Chrome; only worked fully on Firefox.
- Appear.in doesn't support screensharing on Firefox
- There was a delay with the messages appearing on the chatbox.
- When we joined the hangout, there were no names attached to each of the anonymous screens; because of this, the experience felt disconcerting compared to google hangouts.

Based on these experiences, google hangout integration is a better fit at the moment.

Thanks to @distalx and @sergeant-q for jumping in spontaneously to help test appear.in!

**Comment by lpatmo** [comment]
The problem with the hangouts button API (https://developers.google.com/+/hangouts/button) is that once the button renders, it creates a *brand new* hangout link each time the button is clicked on. 

So, two people clicking on the same button that appears will join different hangouts.

I have an alternative solution in the works...

**Comment by PandaWhisperer** [comment]
Just did some reading up on this. Looks like the `wpt:hangouts` package that @wuworkshop suggested just wraps the most basic hangout button behavior. 

I noticed that it’s possible to invite people when the hangout it started. So when the person who creates the hangout launches it, everyone who said they were interested could get an invite automatically, as long as we know their Google ID.

**Comment by PandaWhisperer** [comment]
However, there is a `getHangoutUrl()` method in `gapi.hangouts`: https://developers.google.com/+/hangouts/api/gapi.hangout#functions-in-gapihangout

**Comment by lpatmo** [comment]
In order to use `getHangoutUrl()`, I have to use it in a hangouts app I create and POST it to the codebuddies instance. 

So, first step: create a hangout app.

However, I ran into trouble trying to make my app public. Every time I check the "make my app public" checkbox and save, then reload the page, the box becomes unchecked.

According to the documentation, I need to fill in privacy and terms of service URLs on https://console.developers.google.com/apis/api/plusHangouts/hangouts?project=cb-hangouts. I DID do that, but "make my app public" still isn't working.

Also, how exactly do I find the app_id that I need to fill in in the hangout button? Example:

```<script src="https://apis.google.com/js/platform.js" async defer></script>
<div class="g-hangout" data-render="createhangout"
    data-initial_apps="[{ app_id : '123456789012', start_data : 'dQw4w9WgXcQ', 'app_type' : 'ROOM_APP' }]">
</div>```

Google says it's supposed to be a number, but when I created my `cb-hangouts` app I couldn't find a string of numbers anywhere.

Has the API changed?

**Comment by lpatmo** [comment]
Update: Wow, that took a while, and the google console admin is so confusing. But finally figured out that the reason I wasn't able to make the hangout app public was because I'd selected "web application" instead of "Other" when I was setting up the credentials for the app:

![screen shot 2016-05-10 at 10 13 55 pm](https://cloud.githubusercontent.com/assets/4512699/15170666/bcb8821c-16fc-11e6-80d7-24ce07e2945f.jpg)

I only figured out after reading a nebulous Stackoverflow response about someone saying that they were able to get past an "invalid client" error after they changed this setting from "web browser" to "Other."

Anyway, so now we have a public google hangouts app! Next step: I need to change the code in http://codebuddies.org/hangoutapp/app.xml so that it POSTS the `getHangoutURL()` into our http://cbv2.staging.herokuapp.com staging app.

**Comment by lpatmo** [comment]
Figured out that this is important to the process:

```
<div id="container">

  
  <div class="g-hangout" data-render="createhangout"
    data-initial_apps="[{ app_id : '999356798349', 'app_type' : 'ROOM_APP' }]">
</div>

</div>
<script src="https://apis.google.com/js/platform.js" async defer></script>```

However, I am still not entirely sure how to get this button to render and load in a new hangout URL every time a post on our app is created.

**Comment by lpatmo** [comment]
Good news: created a hangout app that outputs the hangout URL and the ID of the post that it was created from. 

```
      <div class="google-hangout">
            <div class="g-hangout" data-render="createhangout"
            data-initial_apps="[{ app_id : '999356798349', widget_size: '72', start_data: {{_id}}, 'app_type' : 'ROOM_APP' }]"></div>
      </div>
```

Still need to figure out how to POST it to the cbv2 app. @PandaWhisperer suggested using Picker (a meteor package) and doing something like this:

```
Picker.route('/callbacks/google_hangouts', function(params, req, res) {
  // get the hangout ID from somewhere
  Hangouts.update(_id, { $set: { url: params.body.hangout_url }})
  res.send(200);
});
```

**Comment by lpatmo** [comment]
Thanks to @PandaWhisperer for figuring out how to connect the google API app with the cbv2 meteor app. :)

Relevant code:
```
      <div class="google-hangout">
            <div class="g-hangout" data-render="createhangout"
            data-initial_apps="[{ app_id : '999356798349', start_data: {{_id}}, 'app_type' : 'LOCAL_APP' }]"></div>
        </div>

      function init() { // When API is ready... 
        gapi.hangout.onApiReady.add( function(eventObj) {
           if (eventObj.isApiReady) { 
            document.getElementById('showParticipants') .style.visibility = 'visible';
           } 

           /*POST*/
            var hangoutUrl = gapi.hangout.getHangoutUrl();
            var postID = gapi.hangout.getStartData();
            console.log(postID);
            var callbackUrl = 'https://cbv2-staging.herokuapp.com/hangout/'+postID;
              
            var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance 
            xmlhttp.open("PUT", callbackUrl);
            xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
            xmlhttp.send(JSON.stringify({"hangoutUrl": hangoutUrl, "postID": postID}));
  
          }); 
        
      } // Wait for gadget to load. 
```

**Comment by sergeant-q** [comment]
Is this key feature completed? Can we close this issue? @lpatmo

**Comment by lpatmo** [comment]
Yes, let's close this issue!
