### ISSUE TITLE
Choose a hosting provider and deploy the app

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#71]
The leading candidate at the moment (because it's free and support open source projects that apply!) is OpenShift: https://www.openshift.com/

Previously we had discussed hosting on AWS, DigitalOcean, or Galaxy (the official Meteor hosting solution -- which is a little more expensive than the first two options.)

If you have any thoughts on hosting providers, please leave a comment.

**Comment by sergeant-q** [comment]
For **OpenShift**. Is the set up and deployment for Meteor apps straightforward and well supported? I used it a while back and it was never easy to get things up and running.  A lot of 'dev ops' work needed to handled by the developer.  

The whole point of these **PaaS** providers is to remove that headache and provide an almost ready-to-use server/platform to run your applications.  My experience with OpenShift has always been rocky and a ton of administrative tasks required to just deploy an app. I'm hoping things have improved since then.

Worrying less about the infrastructure and more on code itself is always the goal. Of course, there will always be a need to customize deployments and set ups but the hope is that the platform offers stable, effective and easy workflows.  

Lastly, the most important point here. It all comes down to our basic requirements and if it fits the bill.  Do we care about auto-scaling for example? Are we ok with rolling our own server and taking on the configuration, etc. Those are important things to consider.

**Comment by distalx** [comment]
Aws is like paradox of choices. sometimes you end up buying things you don't require.
using OpenShift as a hosting platform won't be easy there are tons of administrative task needs to be done before deployment but it's definitely worth a try. (it's free). Maybe we can automate those administrative task afterwards.
At least we should do one pilot testing with OpenShift. 

DigitalOcean would be perfect if OpenShift don't workout. 

**modulus.io** They provides one year free hosting for startups. and we are just a community driven by free-spirited human beings. If someone from codebuddy could write a compelling letter, they might even sponsor us for a life. 

Galaxy is like the car you always wanted.

**Comment by sergeant-q** [comment]
I'm curious if MDG would even consider sponsoring us for their **Galaxy** offering considering it's a Meteor app we're running!

**Comment by lpatmo** [comment]
Worth a try. :) 

Companies on my potential-sponsors-to-email list now:
- DigitalOcean, MDG, Modulus.io, Slack

Also, thank you everyone for your thoughts on hosting providers! I'm going to try deploying the staging site on OpenShift either today or tomorrow (at least before March 25th), and see how it works out.

**Comment by lpatmo** [comment]
@distalx deployed the a staging version of the app on https://cbv2-staging.herokuapp.com/!

Production will use different credentials. I will reach out to potential sponsors after fixing the hangout button (issue #7) and the profile page.

**Comment by wuworkshop** [comment]
@lpatmo Can this issue be closed?
