### ISSUE TITLE
Home Page Update

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/cb-v2-scratch#96]
Zeplin link https://zpl.io/5qd4v
Logo asset in Zeplin

Use this screenshot for Slack window. Add shadow with CSS!
![slack-window](https://cloud.githubusercontent.com/assets/13413986/14374256/bdea155a-fd08-11e5-85b6-31d43b7d98e6.png)

"Video OFF, microphone OFF, ..." in each column is 13px non-italic and bold **OFF** or **ON**.
![screen shot 2016-04-07 at 9 53 22 pm](https://cloud.githubusercontent.com/assets/13413986/14374495/3fa3e7c2-fd0b-11e5-998e-d5ffbcf27118.png)

Footer with new logo. Text below logo is at 13px
![footer](https://cloud.githubusercontent.com/assets/13413986/14374410/769e7248-fd0a-11e5-974c-a8eb8b13ae3a.png)

**Comment by sergeant-q** [comment]
@adachiu can we do a mock up with the v4 logo?

**Comment by lpatmo** [comment]
I can work on making the updates to the home page.

**Comment by adachiu** [comment]
@lpatmo that's a placeholder logo btw. Although, I'm leaning towards the smiley option 😝
Let me know what y'all think of this home page update.

1. Instead of the "Enter Slack channel," CTA, I suggest we have the "Join Slack channel" CTA with an email address input box. It looks effortless to join Slack this way. 
2. Simplified "What is Slack" hyperlink text. The previous mock had a long "What is Slack" text.
3. Hovering over the hangout cards would show additional information about the specific hangout.  The "Video OFF, Mic OFF" text could be shown only on hover. This helps us declutter and help the user focus on reading the important things first. Chances are, the user would hover cursor over the hangout cards so the hover state would show the hangout icon and the "Video OFF, mic OFF" information. Attached screenshot to show what I mean.
4. Adding a few key FAQ on the home page may be helpful for newcomers to quickly grasp what CB is.


![home-v6](https://cloud.githubusercontent.com/assets/13413986/14667993/d31c29da-0696-11e6-9ef5-7d2d97daea26.jpg)


Idea for hovering over the hangout cards to show more information.

![screen shot 2016-04-20 at 1 42 59 am](https://cloud.githubusercontent.com/assets/13413986/14668462/40eeed24-0699-11e6-9505-96181a05a4e7.png)

**Comment by lpatmo** [comment]
This looks amazing, @adachiu! Two thoughts/questions: 

1) Can you upload this to Zeplin? And I assume the new logo and the fantastic-looking icons for the hangout types will be downloadable via there. 

2) I'm not actually sure if it's possible to have a Slack invite sent through a custom-built form. This problem is the reason we're using http://codebuddiesmeet.herokuapp.com, or https://github.com/rauchg/slackin to get the public invites working. We may need to replace it with the widget. 

Also, IMO this is a good good-for-beginners issue since it's mostly CSS... I might schedule a hangout to work on this exclusively. Wonder if @nestevez7 or @mfhan are interested.

**Comment by wuworkshop** [comment]
@adachiu I like those hangout cards! I think the revised copy is definitely clearer about what CB is and how it works.

**Comment by lpatmo** [comment]
Closed!
